# This file was generated by GoReleaser. DO NOT EDIT.
cask "gormdb2struct" do
  version "1.0.1"

  on_macos do
    on_intel do
      url "https://github.com/dan-sherwin/gormdb2struct/releases/download/v#{version}/gormdb2struct_#{version}_darwin_amd64.tar.gz"
      sha256 "f37e5d23a0d79ad84209348e2a05d7dfc20201464b3a9c107c1f4fe64c88841e"
    end
    on_arm do
      url "https://github.com/dan-sherwin/gormdb2struct/releases/download/v#{version}/gormdb2struct_#{version}_darwin_arm64.tar.gz"
      sha256 "ff22b53466e6740746f480a13df4af109d394c2893c47670fb16ab2e211417af"
    end
  end

  name "gormdb2struct"
  desc "Generate strongly typed GORM models and query helpers from your database schema."
  homepage "https://github.com/dan-sherwin/gormdb2struct"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gormdb2struct"

  # No zap stanza required

end
