# This file was generated by GoReleaser. DO NOT EDIT.
cask "gormdb2struct" do
  version "1.2.0"

  on_macos do
    on_intel do
      url "https://github.com/dan-sherwin/gormdb2struct/releases/download/v#{version}/gormdb2struct_#{version}_darwin_amd64.tar.gz"
      sha256 "66c6f634cf9a7a24e093d11c0dbd53c37eca7ee06cb547fd2296a3e2df2ab40c"
    end
    on_arm do
      url "https://github.com/dan-sherwin/gormdb2struct/releases/download/v#{version}/gormdb2struct_#{version}_darwin_arm64.tar.gz"
      sha256 "68f77608ebd949ce618eed0c20483f910b5f01475c2873b570561896ab91ddc5"
    end
  end

  name "gormdb2struct"
  desc "Generate GORM models, typed gorm.io/gen query helpers, and PostgreSQL wrapper types from an existing schema."
  homepage "https://github.com/dan-sherwin/gormdb2struct"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gormdb2struct"

  # No zap stanza required

end
